# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'balisard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for balisard

  target 'balisard-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'balisardTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'balisard-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for balisard-tvOS

end
